create table hotels
(
    id          int primary key generated by default as identity,
    name        varchar(100) not null,
    address     varchar      not null,
    rating      int check ( rating >= 0 and hotels.rating <= 6 ),
    description varchar
)